@IncidentsDecisionMicroservices.Notifications.Api_HostAddress = http://localhost:5217

GET {{IncidentsDecisionMicroservices.Notifications.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
